# Generated by Django 4.0.4 on 2022-04-11 20:22

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[apps.users.validators.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
