# Generated by Django 4.0.4 on 2022-04-11 20:53

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=9, null=True, validators=[apps.users.models.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
