# Generated by Django 4.0.4 on 2022-04-11 20:57

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, null=True, validators=[apps.users.validators.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
