# Generated by Django 4.0.4 on 2022-04-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_tokentelegrambot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Телеграм ID'),
        ),
    ]
