# Generated by Django 4.0.4 on 2022-04-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentelegrambot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_bot', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
